/*
 * This plugin is simply a mod of Days Since Last Visit 
 * It has not been heavily tested AT ALL!!!
 * Please let me know if you run into any problems -- Kevin Wilson
 */

/*
 * Plugin: Days since First Visit 1.1.H - capture time from first visit
 */
s.getDaysSinceFirstVisit=new Function("c",""
+"var s=this,e=new Date(),es=new Date(),cval,cval_s,cval_ss,ct=e.getT"
+"ime(),day=24*60*60*1000,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10;e.setTime(ct"
+"+3*365*day);es.setTime(ct+30*60*1000);f0='Cookies Not Supported';f1"
+"='First Visit';f2='More than 3 years';f3='1 - 3 years';f4='6 - 12 m"
+"onths';f5='3 - 6 months';f6='1 - 3 months';f7='2 - 4 weeks';f8='1 -"
+" 2 weeks';f9='1 - 7 days';f10='Less than 1 day';cval=s.c_r(c);if(cv"
+"al.length==0){s.c_w(c,ct,e);s.c_w(c+'_s',f1,es);}else{var d=ct-cval"
+";if(d>30*60*1000){if(d>1095*day){s.c_w(c+'_s',f2,es);}else if(d<365"
+"*day+1 && d>1065*day){s.c_w(c+'_s',f3,es);}else if(d<182*day+1 && d"
+">365*day){s.c_w(c+'_s',f4,es);}else if(d<91*day+1 && d>182*day){s.c"
+"_w(c+'_s',f5,es);}else if(d<28*day+1 && d>91*day){s.c_w(c+'_s',f6,e"
+"s);}else if(d<14*day+1 && d>28*day){s.c_w(c+'_s',f7,es);}else if(d<"
+"7*day+1 && d>14*day){	s.c_w(c+'_s',f8,es);}else if(d<1*day+1 && d>7"
+"*day){s.c_w(c+'_s',f9,es);}else if(d<day+1){s.c_w(c+'_s',f10,es);}}"
+"	else{s.c_w(c,ct,e);cval_ss=s.c_r(c+'_s');s.c_w(c+'_s',cval_ss,es)"
+";}}cval_s=s.c_r(c+'_s');if(cval_s.length==0) return f0;else if (cva"
+"l_s!=f1&&cval_s!=f2&&cval_s!=f3&&cval_s!=f4&&cval_s!=f5&&cval_s!=f6"
+"&&cval_s!=f7&&cval_s!=f8&&cval_s!=f9&&cval_s!=f10) return '';else r"
+"eturn cval_s;");

/****Deobfuscated Plugin Code ******/
/*
 * Plugin: Days since First Visit 1.1.H - capture time from first visit
 */
s.getDaysSinceFirstVisit=new Function("c",""
+"var s=this,e=new Date(),es=new Date(),cval,cval_s,cval_ss,ct=e.getTime(),day=24*60*60*1000,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10;"
+"e.setTime(ct+3*365*day);"
+"es.setTime(ct+30*60*1000);"
+"f0='Cookies Not Supported';"
+"f1='First Visit';"
+"f2='More than 3 years';"
+"f3='1 - 3 years';"
+"f4='6 - 12 months;"
+"f5='3 - 6 months';"
+"f6='1 - 3 months';"
+"f7='2 - 4 weeks';"
+"f8='1 - 2 weeks';"
+"f9='1 - 7 days';"
+"f10='Less than 1 day';"
+"cval=s.c_r(c);"
+"if(cval.length==0){"
+"	s.c_w(c,ct,e);s.c_w(c+'_s',f1,es);"
+"	}"
+"else{"
+"	var d=ct-cval;"
+"	if(d>30*60*1000){"
+"		if(d>1095*day){"
+"			s.c_w(c+'_s',f2,es);"
+"			}"
+"		else if(d<365*day+1 && d>1065*day){"
+"			s.c_w(c+'_s',f3,es);"
+"			}"
+"		else if(d<182*day+1 && d>365*day){"
+"			s.c_w(c+'_s',f4,es);"
+"			}"
+"		else if(d<91*day+1 && d>182*day){"
+"			s.c_w(c+'_s',f5,es);"
+"			}"
+"		else if(d<28*day+1 && d>91*day){"
+"			s.c_w(c+'_s',f6,es);"
+"			}"
+"		else if(d<14*day+1 && d>28*day){"
+"			s.c_w(c+'_s',f7,es);"
+"			}"
+"		else if(d<7*day+1 && d>14*day){"
+"			s.c_w(c+'_s',f8,es);"
+"			}"
+"		else if(d<1*day+1 && d>7*day){"
+"			s.c_w(c+'_s',f9,es);"
+"			}"
+"		else if(d<day+1){"
+"			s.c_w(c+'_s',f10,es);"
+"			}"
+"		}"
+"	else{"
+" 		s.c_w(c,ct,e);"
+" 		cval_ss=s.c_r(c+'_s');"
+" 		s.c_w(c+'_s',cval_ss,es);"
+"		}"
+"	}"
+"cval_s=s.c_r(c+'_s');"
+"if(cval_s.length==0) return f0;"
+"else if (cval_s!=f1&&cval_s!=f2&&cval_s!=f3&&cval_s!=f4&&cval_s!=f5&&cval_s!=f6&&cval_s!=f7&&cval_s!=f8&&cval_s!=f9&&cval_s!=f10) return '';"
+"else return cval_s;");